DROP TABLE IF EXISTS account;

CREATE TABLE account (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  user_id NVARCHAR(250) NOT NULL,
  account_number NVARCHAR(250) NOT NULL,
  alias NVARCHAR(250) DEFAULT NULL,
  currency NVARCHAR(250) DEFAULT NULL,
  amount DECIMAL DEFAULT NULL,
);

